project:
  type: website

website:
  title: "Lorenzo Cesconetto"
  navbar:
    right:
      - href: about.qmd
        text: About me
      - icon: linkedin
        href: https://www.linkedin.com/in/lorenzo-cesconetto/
        target: "_blank"
      - icon: twitter-x
        href: https://x.com/l_cesconetto
        target: "_blank"
      - icon: github
        href: https://github.com/lorenzocesconetto
        target: "_blank"
  page-footer: 
    background: secondary
    center: "Copyright 2025, Lorenzo Cesconetto" 
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/lorenzo-cesconetto/
        target: "_blank"
      - icon: twitter-x
        href: https://x.com/l_cesconetto
        target: "_blank"
      - icon: github
        href: https://github.com/lorenzocesconetto
        target: "_blank"
format:
  html:
    theme:
      dark: cyborg
      light: cosmo
    respect-user-color-scheme: true
    css: styles.css
    link-external-newwindow: true
